### ISSUE TITLE
500 Error on click on DIR

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-file-manager#5]
Hello @mominur-helios 

Here is an issue that bumps when I click on a DIR

Please take a look, TY!

---

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/b551e6a9-0e80-4699-a041-911dcf0a0e10)

> Runtime log

```log
Internal Server Error: /file-manager/
Traceback (most recent call last):
  File "D:\work\repo-samples\sample-django-file-manager\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\work\repo-samples\sample-django-file-manager\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\work\repo-samples\sample-django-file-manager\home\views.py", line 40, in file_manager
    files = get_files_from_directory(selected_directory_path)    
  File "D:\work\repo-samples\sample-django-file-manager\home\views.py", line 24, in get_files_from_directory
    'file': file_path.split('/media/')[1],
IndexError: list index out of range
  File "D:\work\repo-samples\sample-django-file-manager\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\work\repo-samples\sample-django-file-manager\home\views.py", line 40, in file_manager
    files = get_files_from_directory(selected_directory_path)
  File "D:\work\repo-samples\sample-django-file-manager\home\views.py", line 24, in get_files_from_directory
    'file': file_path.split('/media/')[1],
IndexError: list index out of range
[03/Jul/2023 10:34:21] "GET /file-manager/?directory=project1 HTTP/1.1" 500 75053
``` 

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/ff34321c-0982-42d0-90be-4c1d56292f57)

**Comment by app-generator** [comment]
Hello @mominur-helios 

Now the `500` error bumps at first access:

> NOTE: I'm using the MEDIA files as they are saved on the repo. Please do the same on your side. 

Thank you! 

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/a23908df-ef5b-4ab7-a3bd-ea1e4dadfe3a)

**Comment by ghost** [comment]
My local machine file structure is same as the repo but I can't get any 500 error @app-generator 
#### file structure
![Screenshot from 2023-07-03 16-51-22](https://github.com/app-generator/sample-django-file-manager/assets/101915710/be8dc53f-1aae-4d60-aa66-b02b731ed8b5)
#### output
![Screenshot from 2023-07-03 16-51-39](https://github.com/app-generator/sample-django-file-manager/assets/101915710/71a66128-fd69-4bc9-8985-0dcf18a88108)

**Comment by app-generator** [comment]
is about the file separator that assumes is a LINUX box.
I just commited the patch, and I confirm I can see the widget.

Please pull.

**Comment by app-generator** [comment]
Validated. Closing.
TY @mominur-helios
